spring:
  messages:
    encoding: UTF-8
  application:
    name: companies
    version: '@project.version@'
  profiles:
    active: dev
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true

      hibernate:
        enable_lazy_load_no_trans: true
        dialect: com.nicico.copper.common.hibernate.CustomOracleDialect
        hbm2ddl:
          schema_filter_provider: com.nicico.copper.common.hibernate.CustomSchemaFilterProvider
    open-in-view: false
    show-sql: true
  liquibase:
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:/db/master-changelog.xml
    enabled: false
  main:
    allow-bean-definition-overriding: true
  activiti:
    rest-api-enabled: true
    history-level: full
    database-schema-update: true
    db-history-used: true
  redis:
    port: 6379
  servlet:
    multipart:
      max-file-size: 1000MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
    context-path: /companies-backend
    session:
      cookie:
        name: App_${spring.application.name}
  forward-headers-strategy: framework
  use-forward-headers: true
  locale: fa

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

nicico:
  token:
    revoke: false
  jpa:
    entity:
      package: com.nicico.companies
  google:
    mail:
      username:
      password:
  mail:
    domain:
    url:
    username:
    password:

  upload:
    dir: /var/nicico/${spring.application.name}/
  workflow:
    update:
      mode: true
  bpmn:
    upload:
      dir: /var/nicico/${spring.application.name}/
---
logging :
  level:
    liquibase : INFO

#feign:
#  client:
#    config:
#      hrm-post:
#        errorDecoder: com.nicico.hse.config.HrmClientConfiguration
#        requestInterceptors:
#          - com.nicico.hse.config.HrmExternalRequestInterceptor
#        connectTimeout: 60000
#        readTimeout: 60000



jasypt:
  encryptor:
    bean: stringEncryptor

bpms:
  service:
    tenantId: companies
    proposal_safety_agent_process_definition_key: aa6d7-a6c2e-aa302
    proposal_workshop_agent_process_definition_key: a77b6-acc3e-acf18
    request_periodic_allocation_workshop_definition_key: af39e-a7ab0-aa4e6
    request_periodic_allocation_individual_definition_key: af39e-a7ab0-aa4e6
    request_case_allocation_definition_key: a095d-a5dd8-adab5
    request_declare_purchase_definition_key: a2edd-a610c-aa24a
copper:
  security:
    policy:
      json:
        filePath: ""
feign:
  client:
    config:
      default:
        connectTimeout: 5000   # 5 seconds
        readTimeout: 10000     # 10 seconds
        loggerLevel: FULL

hrm:
  api:
    base-url: "http://devapp01.icico.net.ir/hrm-backend/"
